#!/bin/sh

# init procfs
mkdir /proc
mount -t proc none /proc
# init sysfs
mkdir /sys
mount -t sysfs none /sys
# insert modules (for network card)
ls -d /etc/modules/* | xargs /sbin/insmod
# setup network
ip addr add 172.16.222.2/24 brd 172.16.222.255 dev eth0
ip link set eth0 up
# setup mdev service (for /dev directory)
mdev -d
# insert gatedefender module
insmod /data/gatedefender.ko

cat <<!

Boot took $(cut -d' ' -f1 /proc/uptime) seconds
System booted, entering shell environment...

!
chmod +x /get-sections.sh
cd /data
exec /bin/sh
